name: Test and Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # o la versión de Node.js que uses

      - name: Install dependencies
        run: npm install # o yarn install

      - name: Create .env.test file
        run: |
          echo "VITE_CONFIG_FIREBASE=${{ secrets.VITE_CONFIG_FIREBASE }}" >> .env.test

      - name: Run tests
        run: npm run test
        env:
          VITE_CONFIG_FIREBASE: ${{ secrets.VITE_CONFIG_FIREBASE }}

  build:
    needs: test # Solo se ejecuta si el job de test pasa
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # o la versión de Node.js que uses

      - name: Install dependencies
        run: npm install # o yarn install

      - name: Build
        run: npm run build # o yarn build
